### ISSUE TITLE
Wrong error message for 'create-basin' command

### ISSUE THREAD

**Issue by lukasmalkmus** [s2-streamstore/s2-cli#96]
I followed the getting started docs and obviously didn't pay attention and tried this:

```
$ s2 create-basin test
error: invalid value 'test' for '<BASIN>': Invalid S2 URI: Missing URI scheme

For more information, try '--help'.
```

So I added the schema:

```
$ s2 create-basin s2://test
error: invalid value 's2://test' for '<BASIN>': Basin name must be between 8 and 48 characters in length

For more information, try '--help'.
```

Ah! So that's the actual problem. Choosing a minimum of 8 characters for the basin name works just fine.

I assume this validation can also live in the rust sdk I assume this cli is built upon? But I just started out with S2 like three minutes ago and didn't dive into the source code yet so just leaving this issue here :) 

Interesting product you guys are building there, very excited!

**Comment by infiniteregrets** [comment]
hi @lukasmalkmus thank you for opening this issue! we have fix up for review, should merged and released in some time https://github.com/s2-streamstore/s2-cli/pull/95 

sorry for any inconvenience!

**Comment by infiniteregrets** [comment]
@lukasmalkmus, we just released a fix. Please let me know if you face any issues!
